source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "puma", ">= 5.0"
gem "sqlite3", ">= 2.1"

# Minimal dependencies for a working Rails app
gem "propshaft"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

group :development do
  gem "web-console"
end
